service: grattr-api

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: prod

functions:
  attributes:
    handler: handler.attributes
    events:
      - http:
          path: "{email}"
          method: get
          cors: true
